# Generated by Django 3.2.10 on 2021-12-24 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=1000, verbose_name='Désignation')),
                ('libelle', models.CharField(blank=True, default='', max_length=100, verbose_name='Libellé')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=1000, verbose_name='Désignation')),
                ('libelle', models.CharField(blank=True, default='', max_length=100, verbose_name='Libellé')),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='libelle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Libellé'),
        ),
        migrations.CreateModel(
            name='Souslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=1000, verbose_name='Désignation')),
                ('libelle', models.CharField(blank=True, default='', max_length=100, verbose_name='Libellé')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lot', verbose_name='Lot')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=1000, verbose_name='Désignation')),
                ('libelle', models.CharField(blank=True, default='', max_length=100, verbose_name='Libellé')),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.categorie', verbose_name='Catégorie')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='souslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.souslot', verbose_name='Sous Lot'),
        ),
    ]
