# Generated by Django 3.2.10 on 2021-12-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211224_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='Categorie',
            new_name='categorie',
        ),
    ]
