# Generated by Django 3.2.10 on 2021-12-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_categorie_equipement_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=1000, verbose_name='Désignation')),
                ('libelle', models.CharField(blank=True, default='', max_length=100, verbose_name='Libellé')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.site', verbose_name='Site')),
            ],
        ),
    ]
