# Generated by Django 3.2.10 on 2022-01-01 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planifie', models.BooleanField(default=False)),
                ('criticite', models.CharField(choices=[('c1', 'C1'), ('c2', 'C2'), ('c3', 'C3')], default='c1', max_length=100)),
                ('statut', models.CharField(choices=[('Enregistrée', 'Enregistrée'), ('Pris en charge', 'Pris en charge'), ('Travaux en cours', 'Travaux en cours'), ('Pending', 'Pending'), ('Résolue', 'Résolue'), ('Clôture', 'Clôturée')], default='Pris en charge', max_length=100)),
                ('objet', models.CharField(default='', max_length=1000, verbose_name='Objet')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('datecharge', models.DateTimeField(default=django.utils.timezone.now)),
                ('datedebut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Début')),
                ('debut', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('pendingstart', models.DateTimeField(default=django.utils.timezone.now, verbose_name='pendingstart')),
                ('endpending', models.BooleanField(default=False)),
                ('pendingend', models.DateTimeField(default=django.utils.timezone.now, verbose_name='pendingend')),
                ('resolu', models.BooleanField(default=False)),
                ('dateresolu', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dateresolu')),
                ('clos', models.BooleanField(default=False)),
                ('datefin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Fin')),
                ('periodicite', models.IntegerField(default=1, verbose_name="Durée d'intervention (jours)")),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categorie', verbose_name='Categorie')),
                ('equipement', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.equipement', verbose_name='Equipement')),
                ('intervenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Intervenant', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lot', verbose_name='Lot')),
                ('site', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.site', verbose_name='site')),
                ('souslot', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.souslot', verbose_name='SousLot')),
                ('zone', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.zone', verbose_name='zone')),
            ],
        ),
    ]
