# Generated by Django 3.2.10 on 2022-02-09 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_tache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='categorie',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categorie', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='site',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='souslot',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.souslot', verbose_name='Sous-Lot'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='zone',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.zone', verbose_name='Zone'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('categorie', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categorie', verbose_name='Catégorie')),
                ('equipement', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.equipement', verbose_name='Equipement')),
                ('lot', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lot', verbose_name='Lot')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.site', verbose_name='Site')),
                ('souslot', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.souslot', verbose_name='Sous-Lot')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mouvement', models.IntegerField(choices=[('1', 'Entrée'), ('2', 'Sortie')], default='1')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.stock', verbose_name='Stock')),
            ],
        ),
    ]
