# Generated by Django 3.2.10 on 2022-02-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220209_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='effet',
            field=models.TextField(blank=True, default='', verbose_name=' Effet sur équipement/ouvrage'),
        ),
        migrations.AddField(
            model_name='tache',
            name='rechange',
            field=models.TextField(blank=True, default='', verbose_name=' Piéces de rechange/Consommable'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='mouvement',
            field=models.IntegerField(choices=[(1, 'Entrée'), (2, 'Sortie')], default='1'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('Enregistrée', 'Enregistrée'), ('Pris en charge', 'Pris en charge'), ('Travaux en cours', 'Travaux en cours'), ('Pending', 'Pending'), ('Résolue', 'Résolue')], default='Pris en charge', max_length=100),
        ),
    ]
