# Generated by Django 3.2.10 on 2022-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20220215_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='imagear',
            field=models.ImageField(null=True, upload_to='interventions'),
        ),
        migrations.AddField(
            model_name='tache',
            name='imagepr',
            field=models.ImageField(null=True, upload_to='interventions'),
        ),
    ]
