# Generated by Django 3.2.10 on 2022-02-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20220215_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='imagear',
            field=models.ImageField(blank=True, null=True, upload_to='interventions', verbose_name=' Image Etat Initiale '),
        ),
        migrations.AlterField(
            model_name='tache',
            name='imagepr',
            field=models.ImageField(blank=True, null=True, upload_to='interventions', verbose_name=' Image Etat Finale'),
        ),
    ]
