# Generated by Django 3.2.10 on 2022-02-16 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_auto_20220215_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criticite', models.CharField(choices=[('c1', 'C1'), ('c2', 'C2'), ('c3', 'C3')], default='c1', max_length=100)),
                ('objet', models.CharField(default='', max_length=1000, verbose_name='Objet')),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('periodicite', models.IntegerField(default=1, verbose_name="Durée d'intervention (jours)")),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categorie', verbose_name='Catégorie')),
                ('equipement', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.equipement', verbose_name='Equipement')),
                ('lot', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lot', verbose_name='Lot')),
                ('site', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.site', verbose_name='Site')),
                ('souslot', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.souslot', verbose_name='Sous-Lot')),
                ('zone', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.zone', verbose_name='Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecharge', models.DateTimeField(default=django.utils.timezone.now)),
                ('datedebut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Début')),
                ('debut', models.BooleanField(default=False)),
                ('clos', models.BooleanField(default=False)),
                ('datefin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Fin')),
                ('imagear', models.ImageField(blank=True, null=True, upload_to='interventions', verbose_name=' Image Etat Initiale ')),
                ('imagepr', models.ImageField(blank=True, null=True, upload_to='interventions', verbose_name=' Image Etat Finale')),
                ('intervenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Intervenants', to=settings.AUTH_USER_MODEL)),
                ('planification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.planification', verbose_name='Planification')),
            ],
        ),
    ]
