# Generated by Django 3.2.10 on 2022-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_intervention_planification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planification',
            name='zone',
        ),
        migrations.AlterField(
            model_name='planification',
            name='periodicite',
            field=models.IntegerField(choices=[('1', 'Hebdomadaire'), ('2', 'Mensuelle'), ('3', 'Trimestrielle'), ('4', 'Semestrielle'), ('5', 'Annuelle')], default=1, verbose_name='Peridicité'),
        ),
    ]
