# Generated by Django 3.2.10 on 2022-02-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20220217_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planification',
            name='periodicite',
            field=models.CharField(choices=[('Hebdomadaire', 'Hebdomadaire'), ('Mensuelle', 'Mensuelle'), ('Trimestrielle', 'Trimestrielle'), ('Semestrielle', 'Semestrielle'), ('Annuelle', 'Annuelle')], max_length=100, verbose_name='Periodicité'),
        ),
    ]
