# Generated by Django 3.2.10 on 2022-02-17 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_planification_periodicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='planification',
            name='datedebut',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Début Planification'),
        ),
        migrations.AddField(
            model_name='planification',
            name='datefin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Fin Planification'),
        ),
    ]
