# Generated by Django 3.2.10 on 2022-02-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20220217_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='s',
            field=models.CharField(max_length=100, null=True, verbose_name='Semaine'),
        ),
    ]
