# Generated by Django 3.2.10 on 2022-02-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20220227_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='s',
        ),
        migrations.AddField(
            model_name='intervention',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='effet',
            field=models.TextField(blank=True, default='', verbose_name=' Effet sur équipement/ouvrage'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='rechange',
            field=models.TextField(blank=True, default='', verbose_name=' Piéces de rechange/Consommable'),
        ),
    ]
