# Generated by Django 3.2.10 on 2022-03-02 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_remove_tache_intervenan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='intervenant',
        ),
        migrations.AddField(
            model_name='tache',
            name='intervenant',
            field=models.ManyToManyField(null=True, related_name='Intervenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
