# Generated by Django 3.2.10 on 2022-03-02 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_auto_20220302_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='intervenant',
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervenant',
            field=models.ManyToManyField(null=True, related_name='Intervenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
