# Generated by Django 3.2.10 on 2022-05-19 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0021_auto_20220302_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ronde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipement', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.equipement', verbose_name='Equipement')),
                ('intervenant', models.ManyToManyField(null=True, related_name='ronde_intervenant', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.site', verbose_name='Site')),
            ],
        ),
    ]
