# Generated by Django 3.2.10 on 2022-05-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_siteequipement'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteequipement',
            name='designation',
            field=models.CharField(default='', max_length=1000, verbose_name='Désignation'),
        ),
    ]
