# Generated by Django 3.2.10 on 2022-05-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_siteequipement_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteequipement',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.zone', verbose_name='Zone'),
        ),
    ]
