# Generated by Django 3.2.10 on 2022-05-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_siteequipement_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteequipement',
            name='Categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categorie', verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='siteequipement',
            name='Lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lot', verbose_name='Lot'),
        ),
        migrations.AddField(
            model_name='siteequipement',
            name='Souslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.souslot', verbose_name='Souslot'),
        ),
        migrations.AlterField(
            model_name='siteequipement',
            name='Equipement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.equipement', verbose_name='Equipement'),
        ),
    ]
