# Generated by Django 3.2.10 on 2022-05-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20220523_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteequipement',
            old_name='Categorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='siteequipement',
            old_name='Equipement',
            new_name='equipement',
        ),
        migrations.RenameField(
            model_name='siteequipement',
            old_name='Lot',
            new_name='lot',
        ),
        migrations.RenameField(
            model_name='siteequipement',
            old_name='Souslot',
            new_name='souslot',
        ),
    ]
