# Generated by Django 3.2.10 on 2022-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20220523_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteequipement',
            name='libelle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Libellé'),
        ),
    ]
