# Generated by Django 3.2.10 on 2022-09-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_siteequipement_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ronde',
            name='categorie',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categorie', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='ronde',
            name='lot',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lot', verbose_name='Lot'),
        ),
        migrations.AddField(
            model_name='ronde',
            name='souslot',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.souslot', verbose_name='Sous-Lot'),
        ),
        migrations.AddField(
            model_name='ronde',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.zone', verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='siteequipement',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.zone', verbose_name='Zone'),
        ),
    ]
