# Generated by Django 3.2.10 on 2022-09-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20220916_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='cout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='siteequipement',
            name='souslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.souslot', verbose_name='Sous Lot'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('Enregistrée', 'Enregistrée'), ('Pris en charge', 'Pris en charge'), ('Travaux en cours', 'Travaux en cours'), ('Pending', 'Pending'), ('Résolue', 'Résolue')], default='Enregistrée', max_length=100),
        ),
    ]
