# Generated by Django 3.2.10 on 2022-09-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20220920_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('Enregistrée', 'Enregistrée'), ('Prise en charge', 'Prise en charge'), ('Travaux en cours', 'Travaux en cours'), ('Pending', 'Pending'), ('Résolue', 'Résolue')], default='Enregistrée', max_length=100),
        ),
    ]
