# Generated by Django 3.2.10 on 2022-09-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_tache_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvement',
            name='date',
        ),
    ]
